### ISSUE TITLE
Ganti nama method jadi snake case

### ISSUE THREAD

**Issue by achmiral** [zaychoer/dfulang#1]
Nama methodnya di ganti jadi snake case aja om biar lebih enak bacanya

```ruby 
def self.total_jenis_kelamin
end
```
https://github.com/zaychoer/daftar-ulang-siswa-baru-ruby-on-rails/blob/8d594c030a2fbc8b104ebaac8aaa2e064766c873/app/models/siswa.rb#L32

**Comment by zaychoer** [comment]
Tks sarannya bang
